[package]
name = "derivable_crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.107"
quote = "1.0.23"
proc-macro2 = "1.0.50"
#vhdl_uart_rs = { path = "../.." }

[lib]
proc-macro = true